CREATE TABLE IF NOT EXISTS kapcsolat_uzenetek (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nev VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL,
  targy VARCHAR(180) NOT NULL,
  uzenet TEXT NOT NULL,
  bekuldo VARCHAR(120) NOT NULL DEFAULT 'Vendég',
  kuldes_ideje DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS galeria_kepek (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fajlnev VARCHAR(255) NOT NULL,
  eredeti_nev VARCHAR(255) NOT NULL,
  feltolto VARCHAR(120) NOT NULL,
  feltoltes_ideje DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
